### ISSUE TITLE
impossible to change host file

### ISSUE THREAD

**Issue by karimwassim** [WereDev/Wu10Man#11]
it's impossible to add blocked microsoft url to host in Redstone 17763

**Comment by WereDev** [comment]
Hi,

Could you please provide some more information.  What do you mean by it being impossible to change hosts file? Are you seeing an error when you try to do so?  If so, what error are you seeing?  Providing a copy of the logs (Help -> Logs) would be helpful as well.

Thanks.

**Comment by WereDev** [comment]
@karimwassim 

Hi.  Do you have any updates on this or additional information so that I can look into this?

Thanks
