### ISSUE TITLE
Error : Access is denied.

### ISSUE THREAD

**Issue by rezaf28** [WereDev/Wu10Man#12]
Error:
Access to the path 'C:\Windows\system32\drivers\etc\hosts' is denied.
Check the logs for more details.
---------------------------
 i run as admin

Log File:
[2019-04-26.log](https://github.com/WereDev/Wu10Man/files/3120406/2019-04-26.log)

**Comment by WereDev** [comment]
Hhmm...seems weird that this would be happening.  I haven't seen this issue before.  Are you running any sort of anti-virus or other software that might be trying to protect that file?

**Comment by WereDev** [comment]
@rezaf28 Are you still running across this issue?

**Comment by pdrive** [comment]
i had this problem. in my case the culprit was the firewall, tinywall. it has an option to lock hosts files

**Comment by WereDev** [comment]
Can you send me a link to Tinywall?  I'll download it and try testing Wu10Man with it.

**Comment by pdrive** [comment]
https://tinywall.pados.hu/

![TinyWall_3__01](https://user-images.githubusercontent.com/57240186/68018666-0032c080-fc9a-11e9-842d-d6a4c1986e2e.png)

**Comment by WereDev** [comment]
I added check when editing Hosts file to see if it's lock and provide more friendly messaging to the user.

#16
