### ISSUE TITLE
App will not start

### ISSUE THREAD

**Issue by DKANomad** [WereDev/Wu10Man#13]
I installed and ran and installed version 2.1.0 successfully and disabled windows update along with all services.

However now that I am trying to re-enable the services and allow auto updates again, the application will no long start. I have tried reinstalling, rebooting, purging all known locations of data in case something got corrupted, no luck.

**Comment by erantheathene** [comment]
I have the exact same problem, I tried downloading previous versions and trying too, but still the app wont start. Some help will be greatly appreciated!

**Comment by WereDev** [comment]
I haven't run across this issue before.  When you try to start it, do you get the UAC warning asking for permission to run the app?  Also, can you let me know what build and version of Windows 10 you're running? You should be able to get this from running winver.  Finally, can you send me the latest log file for the app.  It should be at C:\Program Files (x86)\Weredev\Wu10Man\Logs

Thanks.

**Comment by Zak10122** [comment]
> I haven't run across this issue before. When you try to start it, do you get the UAC warning asking for permission to run the app? Also, can you let me know what build and version of Windows 10 you're running? You should be able to get this from running winver. Finally, can you send me the latest log file for the app. It should be at C:\Program Files (x86)\Weredev\Wu10Man\Logs
> 
> Thanks.

I also have the same problem and here is the answers WereDev ask (this is in my case) anyways
-yes it does ask for permission
-here is the windows version 
![Capture](https://user-images.githubusercontent.com/46112290/60772838-eb7f5b00-a0f3-11e9-9d63-24b53e206a6b.PNG)
-the logs: 
[2019-07-07.log](https://github.com/WereDev/Wu10Man/files/3366017/2019-07-07.log)
[2019-07-01.log](https://github.com/WereDev/Wu10Man/files/3366018/2019-07-01.log)
[2019-07-07 (1).log](https://github.com/WereDev/Wu10Man/files/3366019/2019-07-07.1.log)

**Comment by WereDev** [comment]
Thank you for the info.  I'm not running that version of Windows 10 so I'll create a test VM and see if I can reproduce the issue that you're seeing.  If I can't, I'll try add some more logging locations to see if I can capture any additional information.

As a side question, if you press `ALT+SPACE`, does a application menu come up like this?
![image](https://user-images.githubusercontent.com/16233329/60776146-7ad63f80-a0ef-11e9-92f9-92fa29d684d6.png)

**Comment by WereDev** [comment]
Also, if you go into the Task Manager, does Wu10Man show as running?

**Comment by erantheathene** [comment]
[2019-07-08.log](https://github.com/WereDev/Wu10Man/files/3369920/2019-07-08.log)
[2019-07-05.log](https://github.com/WereDev/Wu10Man/files/3369921/2019-07-05.log)
![Untitled](https://user-images.githubusercontent.com/52579991/60836720-fa870b80-a1ce-11e9-8beb-a532f2112422.jpg)

Heres my data. It does ask for permission, and after accepting it pops up in the task manager for 1 second then disappears. No menu comes up when pressing alt + space.

**Comment by WereDev** [comment]
Looks like we have two Pro version (one Pro N) with builds 1803 and 1809.  I'm running Home personally, but my test vm is Pro.  I haven't been able to repro this so far.  I am refactoring a few things that might help and adding some more logging to try to provide me some hints.  I'll hopefully have something ready tonight or tomorrow for release.

As I get that prepped, can I ask what anti-virus or other anti-malware software you might be running?  Given that this app does try to edit the registry and directly alter services, I'm curious if this might be related to those things.

**Comment by erantheathene** [comment]
Thanks a lot Weredev. I'm using plain old microsoft defender, but I turned off realtime protection and all other options before and while using the app. After I restarted the computer the defender was still off, but I couldn't launch the app again. Hope this helps.

**Comment by WereDev** [comment]
I have defender on and generally leave it on, so that does eliminate one potential source of conflict.

I have created a patch release.  I tweaked how the app starts hoping it might do the trick.  If not, I've also added some additional logging to help me identify where the issue might be.  Please give it a try.

https://github.com/WereDev/Wu10Man/releases/tag/v2.1.1

**Comment by Zak10122** [comment]
Well, i tried the new patch release (and it still doesn't work), and here are the new logs that i got after trying it a few times
[2019-07-09.log](https://github.com/WereDev/Wu10Man/files/3373105/2019-07-09.log)
[2019-07-07.log](https://github.com/WereDev/Wu10Man/files/3373102/2019-07-07.log)
[2019-07-09.log](https://github.com/WereDev/Wu10Man/files/3373103/2019-07-09.log)
[2019-07-01.log](https://github.com/WereDev/Wu10Man/files/3373104/2019-07-01.log)

also when i tried clicking alt+space a few times, but the app does open in the task manager and with it a windows problem reporting open
![Capture](https://user-images.githubusercontent.com/46112290/60890795-f05b2080-a253-11e9-8cd2-179026835b42.PNG)

**Comment by WereDev** [comment]
Thank you for the logs, those are extremely helpful.  It seems that there is some issue with the Services control loading.  Oddly, it's now throwing any sort of exception.  Might be that the Windows Problem Report is grabbing it.  Not sure how to get access to that info.

I will work on another update to try to capture that exception and get it in the log.  I'll also go through my code and see what assumptions I might be making that are causing problems.  I will try, but I'm not sure if I can get another update out tonight.  Worst case is that I will be able to get one out sometime later this week.

**Comment by erantheathene** [comment]
Tried the new patch, here's my log. Still not opening. Thanks for the hard work man.
[2019-07-09.log](https://github.com/WereDev/Wu10Man/files/3374092/2019-07-09.log)

**Comment by WereDev** [comment]
Thanks for you logs as well, erantheathene .  You're having the same issue as Zak10122; it's dying while setting up Services.

I didn't find any place in my code that I would expect new errors to be thrown from.  I did identify some additional places that I can add logging to gather more information though.  I've included that in v2.1.2 (https://github.com/WereDev/Wu10Man/releases/tag/v2.1.2) if you would like to try that.  I also added a try/catch around that block so that if the issue is where I expect, the application will at least start, though minus one or more of the Service toggles.

Please try 2.1.2 and let me know how it goes.  I'd appreciate log files when that run as I'm now expecting some actual exceptions to be logged which will be helpful.

As another request, could you run the below commands in a command prompt (cmd)?
```
sc queryex type= service state= all | find /i "wuauserv"
sc queryex type= service state= all | find /i "TrustedInstaller"
sc queryex type= service state= all | find /i "WaaSMedicSvc"
sc queryex type= service state= all | find /i "ShouldNotExist"
powershell "(Get-ItemProperty \"HKLM:SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full\").Release"
```

They should return information regarding whether each of those services exists.  The last line will tell me the build of .Net that you're running as there's a slim chance that the issue might be there.  This is built for 4.6.2 so there shouldn't be any issues, but just in case.

The output should look something like this:
```
C:\Users\WereDev>sc queryex type= service state= all | find /i "wuauserv"
SERVICE_NAME: wuauserv

C:\Users\WereDev>sc queryex type= service state= all | find /i "TrustedInstaller"
SERVICE_NAME: TrustedInstaller

C:\Users\WereDev>sc queryex type= service state= all | find /i "WaaSMedicSvc"
SERVICE_NAME: WaaSMedicSvc
DISPLAY_NAME: WaaSMedicSvc

C:\Users\WereDev>sc queryex type= service state= all | find /i "ShouldNotExist"

C:\Users\WereDev>powershell "(Get-ItemProperty \"HKLM:SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full\").Release"
394802
```

Thanks!

**Comment by DKANomad** [comment]
Sorry for the delayed response, I managed to work around the issue by grabbing the master branch and looking for the error. 

From what I can see the error originates from the `ServiceEditor` class, in the `IsServiceEnabled()` method.

It seems that when disabling certain services it's removing them so when you try and restart the program that throws an error as it's unable to find the service/module.

The workaround I used was hard coding that method to return false, the app then starts. I was able to re-enable everything fine, and with a reboot everything was back to normal it would seem.

I realise this is quite ambiguous, I'm at work and just remembered that I needed to respond to this!

**Comment by WereDev** [comment]
Weird.  So, on the file system, I do rename the primary DLL of each service as Microsoft as implemented several processes that will reset permissions and service properties back to what they were.  This overrides setting a service to `Disabled` or changing permissions to something invalid which is what version 1.x of this app used to do.  By renaming, it can't restart the service as the file is missing.  I just preface it with `Wu10Man_`.  Anyway, I haven't had that become an issue in any of my testing, and I personally use this app all the time.  Interesting that this would crop up here.

Part of `IsServiceEnabled` looks for the file that is set in the Registry as the entry point for the service.  I imagine that is the potential source of error.  Anyway, if you have a fix that handles this gracefully, please send me a PR.  Or if you can send me the exception that you're seeing, I can come up with a fix on my end.  Either way, good work on finding the issue, and thank you a lot for your time and feedback on this.

**Comment by Zak10122** [comment]
Thanks for the help WereDev, i tried the new version and it works, i can enable the auto update!
i tried running the code that you gave in the cmd and here is my output:

```
C:\Users\sts jijel>sc queryex type= service state= all | find /i "wuauserv"
SERVICE_NAME: wuauserv

C:\Users\sts jijel>sc queryex type= service state= all | find /i "TrustedInstaller"
SERVICE_NAME: TrustedInstaller

C:\Users\sts jijel>sc queryex type= service state= all | find /i "WaaSMedicSvc"
SERVICE_NAME: WaaSMedicSvc
DISPLAY_NAME: WaaSMedicSvc

C:\Users\sts jijel>sc queryex type= service state= all | find /i "ShouldNotExist"

C:\Users\sts jijel>powershell "(Get-ItemProperty \"HKLM:SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full\").Release"sc queryex type= service state= all | find /i "wuauserv"

C:\Users\sts jijel>sc queryex type= service state= all | find /i "TrustedInstaller"
SERVICE_NAME: TrustedInstaller

C:\Users\sts jijel>sc queryex type= service state= all | find /i "WaaSMedicSvc"
SERVICE_NAME: WaaSMedicSvc
DISPLAY_NAME: WaaSMedicSvc

C:\Users\sts jijel>sc queryex type= service state= all | find /i "ShouldNotExist"

C:\Users\sts jijel>powershell "(Get-ItemProperty \"HKLM:SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full\").Release"
461814
```

**Comment by DKANomad** [comment]
Got the latest version and it appears that the startup issue has been fixed. So if you would like to close this issue that's fine.

However I don't think the actual issue has been rectified as now when I start the app after disabling the auto-update policy and also disabling all 3 services. I am left with 1 of the services missing from list. See below

![missingService](https://user-images.githubusercontent.com/22933082/60965364-030b4d80-a359-11e9-8d93-13ea3e300643.PNG)

Is this intended behavior? When I re-enable the other 2 the third does not reappear. My initial fix for the crash does make it reappear.

![hardCode](https://user-images.githubusercontent.com/22933082/60965519-65644e00-a359-11e9-84cb-7de148d3e928.PNG)

**Comment by WereDev** [comment]
I figured it was only one of the services that was failing out, so I was expecting one of them not to show up.  Could you send me the logs from when it wasn't showing up?  It should have captured the actual exception.  In the mean time, I can set a try/catch in IsServiceEnabled().  You are right that it is part of what sets switches on startup of the app so I can't leave it hard-coded to false.

Thank you for your help on this!

**Comment by WereDev** [comment]
Thank you to everyone for your feedback and help thus far.  I know this can be frustrating.  Thank you especially to @DKANomad for identifying exactly where in code the exception is coming from.  This has been key since I haven't been able to replicate this issue locally.

Taking his discovery into account, I have created a new release that should restore all the functionality.  https://github.com/WereDev/Wu10Man/releases/tag/v2.1.3

As always, keep the logs coming as you see issues!

Thanks again!

**Comment by DKANomad** [comment]
Here is the error that occurred initially, found it in the Logs.

`2019-07-10 21:21:11.0297 ERROR System.ComponentModel.Win32Exception: The system cannot find the file specified
   at System.ServiceProcess.ServiceController.get_StartType()
   at WereDev.Utils.Wu10Man.Editors.ServiceEditor.IsServiceEnabled() in ServiceEditor.cs:line 67`

Hope this helps you track down the issue.

**Comment by WereDev** [comment]
Hey!  Thanks for this.  I was afraid that this might be the error.  I don't think I can fix that as that's a .Net thing.  I'm guessing that some versions check for the file while others don't?

Anyway, version 2.1.3 that I put out yesterday should handle this more gracefully, allowing the app to run with all of the services showing.  You should still be able to enable/disable each of them.  If not, please let me know.

**Comment by WereDev** [comment]
Hey @DKANomad I just wanted to check to see that everything is working for you now.

Thanks.

**Comment by DKANomad** [comment]
Yeah everything is working, I was able to enable everything using my hard coded false, it just stops the switches from updating. I have an idea about how a work around, in regarding the switches. It's might not be pretty but it could work. I will do some testing when I get chance and submit a PR once I have something you can use.

**Comment by WereDev** [comment]
Did 2.1.3 not fix the issue for you?  I set that up so that even if the line you sent me throws an exception, it should still show up in the list and correctly let you enable/disable the service.

**Comment by DKANomad** [comment]
Let me double check that

**Comment by DKANomad** [comment]
Confirming 2.1.3 does not fix the issue with the row disappearing in the services dialog. The app does start now though.

**Comment by WereDev** [comment]
Well crap.  I'll take another look.

**Comment by WereDev** [comment]
Ok, I think I found the issue.  I had put code to capture the exception and handle it gracefully, but it was higher up in the code.  I forgot that I'm using the IsEnabled elsewhere as well and it wasn't caught there.  If I put it at the spot that you pointed out, then it should work better.  Since you're working on the code itself, can you update the function that you hardcoded `false` to this instead?

```
public bool IsServiceEnabled()
        {
            try
            {
                return _serviceController.StartType != ServiceStartMode.Disabled;
            }
            catch (Win32Exception)
            {
                return false;
            }
        }
```

Let me know if this works.  If it does, I'll release a new patch version.

Thanks!

**Comment by DKANomad** [comment]
That was exactly what I was going to submit, I have added the code and will test it as soon as I get a chance

**Comment by WereDev** [comment]
Haven't heard back, so I assume this tweak was working.  I added to the latest version as well.

https://github.com/WereDev/Wu10Man/releases/tag/v3.0.1
