### ISSUE TITLE
windows module installer turns ON automatically

### ISSUE THREAD

**Issue by pdrive** [WereDev/Wu10Man#15]
windows module installer keeps getting re enabled. not sure why. as soon as it boots, it is off but after  ~couple of hours, when i relaunch the app it's on again

only happening with 1 pc.. not sure what could be causing this

**Comment by WereDev** [comment]
Are you only disabling the Windows Module Installer? Or are you disabling everything?

Also, can you send me your log files?

Thanks.

**Comment by pdrive** [comment]
How do I get the log files? 

Disabling everything.
I think it could be because I had a pending windows updates ready to install? 

I've since then removed C:\Windows\SoftwareDistribution folder which contains pending windows updates ready to install. 

Not sure if this fixed the module installer getting turned on. I'll know tonight

**Comment by pdrive** [comment]
It didn't turn back on today. After what I did yesterday. 

Logs in the previous comment

**Comment by WereDev** [comment]
Thank you for the logs.  Nothing looks too out of the ordinary, though it does look like you're behind a bit on windows updates.

Not sure what would be in Software Distribution that would reenable Trusted Installer other that something that was there and trying to execute on boot from a pending update like you mentioned.

There is the WaaSMedicSvc that reenables Windows Updates if not also disabled.  It's possible there is something like that for Trusted Installer as well.  I will do some digging to see what I can find that might be reenabling that.

**Comment by pdrive** [comment]
It's on again. Here's the log
![IMG_20191102_163959](https://user-images.githubusercontent.com/57240186/68073395-1753da00-fd90-11e9-9831-38d330e2c9ec.jpg)
[2019-11-02.log](https://github.com/WereDev/Wu10Man/files/3800649/2019-11-02.log)

**Comment by pdrive** [comment]
Not sure if it's relevant but I've noticed a weird exe trying to connect to Microsoft servers (blocked). 
**sedsvc.exe 52.156.204.185**

> These files are copied by a reliability update KB4023057 for Windows 10 to improve Windows Update Service components in your machine. 
https://www.askvg.com/what-are-sedsvc-exe-sedlauncher-exe-files-and-rempl-folder-in-windows-10/

**Comment by WereDev** [comment]
My research confirms the information you provided in the link.  I will work on an update tonight that will include that service in the list of things that I'm checking. On the plus side, the Trusted Installer service, by it self, shouldn't allow for updates to be applied to your system.  The two important ones are the Windows Update service and Windows Update Medic Service.

Interesting thing is that not all systems appear to have that.  I don't have that service on my home or work machines and they're both running 1903.  Do you remember if you manually installed that service as it looks like it's part of a service pack and not a typical download?

**Comment by pdrive** [comment]
nope. i didnt manually install anything. i think the system updated once when i first got it a few weeks ago. it's a fanless minipc similar to this one: https://amzn.to/2NexDOk  but 8gb ram 
i assume it comes from china.

my asus laptop (Windows 10 Home Version 1809 Build 17763) from 2013 also has that folder 
![deskptopservice](https://user-images.githubusercontent.com/57240186/68166327-55085c80-ff62-11e9-9611-edeeeb512ce9.JPG)

maybe... this service is only for europe/spain? xD
i have no idea, just brainstorming.

since i've turned on the firewall, all of the issues went away
most of the problems probably came from the fact that i had ready to install updates when i disabled windows updates services

**Comment by WereDev** [comment]
So it looks like it was something that was installed for Windows versions 1507 through 1809 released a couple months ago.  https://support.microsoft.com/en-us/help/4023057/update-reliability-for-windows-10-versions-1507-to-1809.  That would be why I don't have it on my machines, as I updated to 1903 earlier in the year.

Given that, it's going to take me longer to come up with an update as I'll need to setup a VM with the older version of Windows to test this on.

**Comment by WereDev** [comment]
Hey, wanted to check in and let you know what's going on.  My computer has decided to be difficult.  I'm waiting for a new part to come in so it's going to be a bit longer before I can get this fix out.

**Comment by WereDev** [comment]
Thanks for your patience on this.  Got everything running and a VM setup.  This should be fixed now.  Check out the latest release.

https://github.com/WereDev/Wu10Man/releases/tag/v3.1.0

**Comment by pdrive** [comment]
thanks!

i'll try it out and let you know
