### ISSUE TITLE
Defer Feature Updates for 99999 days?

### ISSUE THREAD

**Issue by pstein** [WereDev/Wu10Man#34]
As far as I know MS allows currently only to defer a maximum of 365 days for Feature Updates.

So if I enter in Win10Man 99999 days what will happen after 365 days?

Is the internal maximum of 365 days ignored or my value of 99999 days?

**Comment by WereDev** [comment]
The maxes allowed by Microsoft I'm pretty sure are just part of their UI and not part of the actual functionality of Pause.

The "Pause updates until" boxes are a date and saved to the Registry as such, so any date should be respected.  No updates will be performed until that date.

The "Number of days to defer updates" are how long to delay the current round of updates.  So if an update comes out on 17-Nov and you put 7 days as a deferment, then your system will grab them on 24-Nov.  Subsequently the updates coming out on 17-Dec will also be delayed 7 days and be applied on 24-Dev.  I don't think there is a max that Microsoft looks for during runtime, instead relying on the UI to constrain user settings, but it's not something easily tested as it's hard to wait 99999 days to see what Windows will do. heh

Effectively Pause is like turning updates off with a scheduled switch to turn it back on on X day.  Deferment basically lets your system work in arrears for X number of days.  The later is useful if you want to see if the update has breaking changes by reading reviews and posts before automatically applying it to your system.
