### ISSUE TITLE
Wu10Man_wuaueng.dll

### ISSUE THREAD

**Issue by 89z** [WereDev/Wu10Man#42]
If I start the program, and click the Windows Update button, I get this:

~~~
Access to the path 'C:\Windows\system32\Wu10Man_wuaueng.dll' is denied.
~~~

I tried running the program normally, and also as admin.

**Comment by 89z** [comment]
As a workaround, it seems if I enable one or both of the other services first (Windows Modules Installer or WaaSMedicSvc) then I can enable Windows Update after that.

**Comment by englishextra** [comment]
Gents, let me add my 5 cents:

This is NOT a tool that you just install and enjoy its functionality

You should use it only if you really understand how windows update enforces its process

For starters you have to install wu10man right after fresh install of Windows and having disabled windows defender but prior to that you have to add wu10man to exceptions and reboot the system twice.

You cannot just install this tool on already working and tuned up machine and expect no issues.

Also please specify what version of wu10man has the issue you described when opening the issue.

**Comment by ihor-drachuk** [comment]
I had the same issue and solved it. Try to change file permissions for `Wu10Man_wuaueng.dll` (allow user access).

If you don't have enough rights to change file permissions, try to gain higher access rights with `cmd` started via [NSudo](https://github.com/M2Team/NSudo/releases) and then change file permissions from this elevated `cmd` for those file. It helped me.

**Comment by WereDev** [comment]
Bit late to the game here.  I don't think this would be a file permission issue.  The file permissions should already be handled by Wu10Man on it's own.  There's a couple layers where Wu10Man will try to make sure file permissions are set correctly, though with Wu10Man running with Admin permissions, this generally isn't an issue.

It seems more likely to me that it's a file lock issue meaning something has a lock on the file which is preventing the rename.  The first thing I might try is rebooting.  If you disabled and then immediately tried to reenable the Windows Update service, it's possible that Wu10Man is keeping a file lock from itself.  Or there is some other application, perhaps anti-virus or something, that has a lock on the file.  Short of crawling through some task lists or trying to identify what program has a lock rebooting is usually easier.

If this doesn't work for you or you are still having issues, can you reproduce the issue and then send me the log file?

**Comment by 89z** [comment]
Thanks for the replies - I was trying to get Docker working on my computer, but I dont need it anymore. Thanks again
