### ISSUE TITLE
Facing a small issues.

### ISSUE THREAD

**Issue by A1053Bb** [WereDev/Wu10Man#44]
Issues are :-
1) When, I am opening microsoft store, it is not checking for any app updates. Does it depend on windows updates ?
2) In settings, windows updates says last checked for updates with latest time and telling all are upto date. How, Can it check for updates if all the services are disabled by wu10man ?

**Comment by WereDev** [comment]
I'm not entirely sure how the Windows App Store works under the hood, but it does use the Windows Update and Trusted Installer services to do it's updates and installs.  In order to update those applications, you would need to temporarily reenable those services.

If you're worried about Windows itself updating when you do so, you can try the Pause Updates tab.  I know this will pause the Windows Update functionality though fair warning, I'm not sure if this also pauses Windows App Store updates, or if forcing a Windows App Store update will unpause the Windows Updates.

**Comment by A1053Bb** [comment]
> I'm not entirely sure how the Windows App Store works under the hood, but it does use the Windows Update and Trusted Installer services to do it's updates and installs. In order to update those applications, you would need to temporarily reenable those services.
> 
> If you're worried about Windows itself updating when you do so, you can try the Pause Updates tab. I know this will pause the Windows Update functionality though fair warning, I'm not sure if this also pauses Windows App Store updates, or if forcing a Windows App Store update will unpause the Windows Updates.

Thank you very much, I enabled all the services, and paused the update for 80 years. Now, I am able to do app updates in microsoft store, and it haven't unpaused windows updates. 
You have made such a wonderful and easy to use software. I appreciate your hard work in developing this software.

**Comment by A1053Bb** [comment]
> I'm not entirely sure how the Windows App Store works under the hood, but it does use the Windows Update and Trusted Installer services to do it's updates and installs. In order to update those applications, you would need to temporarily reenable those services.
> 
> If you're worried about Windows itself updating when you do so, you can try the Pause Updates tab. I know this will pause the Windows Update functionality though fair warning, I'm not sure if this also pauses Windows App Store updates, or if forcing a Windows App Store update will unpause the Windows Updates.

Another issue, in event viewer there are some entries stating that WaasMdcAgent is terminated with error : file not found, though I have turned off Remediation in Beta - Scheduler option.

**Comment by WereDev** [comment]
When disabling the services, Wu10Man renames some of the underlying files to get around some of the shenanigans Microsoft uses to try to force updating anyway.  If the scheduled tasks are still enabled then you will see that error when the tasks try to run.  If you disabled the task in Wu10Man as well, then either something reenabled it or there is something else (perhaps another task) trying to run that service.  I'll see if I can dig anything up.

**Comment by WereDev** [comment]
Looks like theres a couple other scheduled tasks that I either missed or are new.  I'll include them in the next release.

**Comment by WereDev** [comment]
Just pushed a release with a tweaked set of Scheduled Tasks.  Let me know if that helps.
