### ISSUE TITLE
Is it possible for this epic project to support i18n?

### ISSUE THREAD

**Issue by lupohan44** [WereDev/Wu10Man#47]

**Comment by WereDev** [comment]
I can look into it.  I don't spend a lot of time maintaining this much anymore.  What language would you be interested in first?

**Comment by lupohan44** [comment]
Simply move all English text into one separate file(like an external xml file or something) is enough. We can help translate to other languages after that.

**Comment by WereDev** [comment]
I had that partially done and on my todo list, but I won't be working on this project anymore so sadly I won't be finishing this feature.  Sorry.
