### ISSUE TITLE
Declutter removes Mail app even though it wasn't checked?

### ISSUE THREAD

**Issue by Darkmaster006** [WereDev/Wu10Man#49]
So out of the blue, after removing some of the apps with the 'declutter' function, it seems the mail app has also been removed even though this wasn't even an option in the first place. This shouldn't happen, correct? So I thought I'd report it. (Also, stuff like 'Your Phone' and 'Cortana' is also not available to be deleted, which would be cool to do) (Also, XBox Beta UI is still there even after it says it's been removed, not sure if it's been, though it doesn't show up in apps so I guess it is).

**Comment by WereDev** [comment]
Wu10Man doesn't try to remove Mail so I'm not sure why that would disappear from your system unless it was connected to something else.  You can see the list of packages that Wu10Man tries to remove by checking the app.settings.json file that was installed in the Wu10Man folder, or the version here on GitHub (https://github.com/WereDev/Wu10Man/blob/master/Wu10Man/app.settings.json).

I will look into adding "Your Phone" to the list of removable items.  I know that removing Cortana is super tricky as so much of is baked into areas of Windows.  I'm not even sure if it is removable, but I'll dig into that a bit as well.

**Comment by Darkmaster006** [comment]
> Wu10Man doesn't try to remove Mail so I'm not sure why that would disappear from your system unless it was connected to something else. You can see the list of packages that Wu10Man tries to remove by checking the app.settings.json file that was installed in the Wu10Man folder, or the version here on GitHub (https://github.com/WereDev/Wu10Man/blob/master/Wu10Man/app.settings.json).
> 
> I will look into adding "Your Phone" to the list of removable items. I know that removing Cortana is super tricky as so much of is baked into areas of Windows. I'm not even sure if it is removable, but I'll dig into that a bit as well.

Agreed, I'm as surprised as you are. But it really did get deleted, maybe it's connected to something else (Alarms?). Your Phone removal would be cool to have. Cortana, yes, it's really tricky as far as I know, but it'd be cool to have it as removed as possible. Thank you very much.

**Comment by WereDev** [comment]
I haven't been able to reprodue this or found any other issues along this line so I'll close this for now.  Feel free to reopen or create a new issue if you see something similar again.
