### ISSUE TITLE
Add Update Orchestrator service to the list

### ISSUE THREAD

**Issue by RaXorX** [WereDev/Wu10Man#57]
Is it possible to add update orchestrator to the list of services that can be disabled?
I don't want to disable the services, I simply don't wish the windows update to do it's own scanning as I use Wumt to manage my updates manually. I don't know what can be done, although my suggestion to add the service in the list does nothing to what I want. I noticed though with Update Orchestrator disabled, the windows update will simply be 99.99% disabled. 

I tried extending the time for the pause interval using wu10man, but it didn't take any effect and still resumed updates after the original intended 1 week of pause. Also the update orchestrator scheduled tasks keep enabling themselves.

**Comment by maru7777** [comment]
> Is it possible to add update orchestrator to the list of services that can be disabled? I don't want to disable the services, I simply don't wish the windows update to do it's own scanning as I use Wumt to manage my updates manually. I don't know what can be done, although my suggestion to add the service in the list does nothing to what I want. I noticed though with Update Orchestrator disabled, the windows update will simply be 99.99% disabled.
> 
> I tried extending the time for the pause interval using wu10man, but it didn't take any effect and still resumed updates after the original intended 1 week of pause. Also the update orchestrator scheduled tasks keep enabling themselves.

so what version are you using? such as 20H1, 21H2..

**Comment by WereDev** [comment]
Most of what Wu10Man looks for in various services and such is actually kept in the configuration file.  You should be able to add additional services that it can shut down for you.  Though I obviously haven't tested it so use it with an abundance of caution.
