### ISSUE TITLE
Please add Command-line interface (Especially for portable version)

### ISSUE THREAD

**Issue by amymor** [WereDev/Wu10Man#58]
Hello and thank you for such a great app.
1. you know the store and xbox app need Windows Update service for downloading app updates and games. so i wanna create a script for toggle enable/disable WU service and then add it somewhere (like Desktop right-click context menu) for quick access to it.
2. Also sometimes i need the TrustedInstaller service for some tweaking. when its off, tools like Nsudo and Advancedrun cant run anything as TrustedInstaller. so it would be great if add a Command-line option to toggle it too in Desktop right-click context menu.
3. when we enable WU, it sometimes automatically creates a scheduled task so we should check "BETA -Scheduled Task" tab every time enable WU. its too annoying. so if we have a Command-line interface, we can disable this scheduled task every time we toggle WU on/off.
However i can create a batch script for 2. & 3. myself, but i found Wu10man do something strange for disabling WU service because i noticed its info under Services.msc changed to <Failed to Read Description. Error Code: 2 > . also noticed that when i disable WU with Services.msc, sometimes it automatically re-enables. so createing a script for toggle it with normal metods (like reg add "HKLM\SYSTEM\CurrentControlSet\Services\wuauserv" /v "Start" /t reg_dword /d 4 /f ) cant disable it permanently.
it would be graet if you add a command-line for toggle WU service. also if you let me know what WU10man does when disabling the WU service, i might be able to create a batch script for it as well. (im not a dev so cant understant your C# source)
anyway thanks for your work and sry for my bad eng

**Comment by amymor** [comment]
For anyone interested, I created a batch script that adds an option to your desktop context menu to enable or disable Windows Update.
I share it here:
[1Click-Update](https://github.com/amymor/1Click-Update)

**Comment by WereDev** [comment]
Once upon a time, I had this on my todo list.  But I won't be working on this project anymore so I won't be able to add this.
