### ISSUE TITLE
Wu10Man v.4.4.0 with Windows 11?

### ISSUE THREAD

**Issue by vega69-ux** [WereDev/Wu10Man#61]
Does Wu10Man v.4.4.0 support/work with Windows 11? If not, is there an alternative available for Windows 11?

**Comment by wmjlxl** [comment]
i have the same question...

**Comment by soopacrucial** [comment]
> Does Wu10Man v.4.4.0 support/work with Windows 11? If not, is there an alternative available for Windows 11?

The developer may have a better answer, but it seems to work for me in Windows 11.

**Comment by WereDev** [comment]
I used Windows 11 for a while and this seemed to work, though I've gotten a couple reports of things not working with the latest updates.  I've transitioned away from Windows to Linux so I haven't tested this several months.  If it works for you, great.  If not, know that I'm not working on this project anymore so you might need to find something else that can shut down the pesky Windows Update.
