### ISSUE TITLE
Building from Clone. New to this project.

### ISSUE THREAD

**Issue by burslem2017** [WereDev/Wu10Man#63]
Hi WereDev,

New to this project. However interested in seeing this work and block windows updates. I am having some issues building in Visual 2022 studio the project after cloning. Much appreciate any help on building this. Great job on doing this. The missing .pfx files missing. How did you build them and lastly any chance of instructions on building.

![image](https://user-images.githubusercontent.com/92032792/226986966-d41c8e58-5091-478c-a60e-0f30f85eef69.png)

**Comment by WereDev** [comment]
I'm guessing this is very late, but just in case, you need to disable the signature keys in the specific projects.  Its failing to find that and thus failing to build.  Disabling it should allow you to build, it just won't be signed.
