### ISSUE TITLE
The disable win defender, and disable win update are not working

### ISSUE THREAD

**Issue by dannywpeto** [WereDev/Wu10Man#66]
The disable win defender, and disable win update are not working or Microsoft has made a work around.
 win update keeps deleting all my files and (I think by remote wiped my external dive) they need to stay out of peoples comps.

**Comment by WereDev** [comment]
Yeah, Windows and Microsoft is a pain like that.  Sadly, I won't be working on this anymore so you might need to prod the internet for another option.
