### ISSUE TITLE
Error turning off Windows Update, Cannot open wuauserv service on computer '.'. 

### ISSUE THREAD

**Issue by DannyJS1** [WereDev/Wu10Man#9]
Encountered this error trying to disable the Windows Update option, any idea? I attached the text file log so you can take a look at it. Thanks.

**Comment by DannyJS1** [comment]
Sorry, the file didn't attach. Here it is.
[wu10log.txt](https://github.com/WereDev/Wu10Man/files/2744029/wu10log.txt)

**Comment by WereDev** [comment]
Sorry for the delayed response...I'm apparently not getting notices from Github when someone opens an issues.  I'll take a look.

**Comment by WereDev** [comment]
@DannyJS1 I assume that you're running Windows 10?  Can you tell me anything else about your system?  Are you running Home, Pro, Enterprose, etc?  Do you know what build you have?  (You can get this by running winver.)

**Comment by DannyJS1** [comment]
If the image doesn't show, it's Windows 10 Home version 1803, OS Build 17134.523.

**Comment by WereDev** [comment]
So it looks like there are actually two errors going on.  One is that it can't seem to get access to the service to disable it.  The other is then that it can't find the file associated with the service.  This is quite strange as if it didn't exist, the service wouldn't show up as an option at all.  That tells me that something on your system is actively blocking access which is interesting.

What sort of anti-virus and/or malware protection are you running?

In the mean time, I'm trying this on a couple test VMs to see if I run into anything similar.  I may also release a minor update soon to try to enhance the logging further.

**Comment by WereDev** [comment]
@DannyJS1 Also, is the application prompting you to run as Administrator?  And are you allowing it to do so?

**Comment by WereDev** [comment]
@DannyJS1 I was able to run into this issue if I tried to use Wu10Man WHILE a Windows Update was taking place.  Does that match your experience?  Are you able to switch the service off now or are you still having the issue?  I assume you've tried rebooting as well?

**Comment by WereDev** [comment]
@DannyJS1 

Hey.  I wanted to follow up and see if you had time to go over my previous questions.  Are you still having issues with this?

Thanks.
